name: Devops lab workflow
on:
 workflow_dispatch: #allows manual trigger from github UI
jobs:
 echo-steps:
   runs-on: ubuntu-latest
   steps:
    - name: first step
      run: echo "this is the first step"
    - name: second step
      run: echo "this is the first step"
